name: "Pipeline do Lambda"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lambda-auth:
    name: "Lambda Auth"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@13.0
        with:
          cli: 1.11.1.1435              # Clojure CLI based on tools.deps
          lein: 2.11.2                  # Leiningen

      - name: Cache clojure dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          key: cljdeps-${{ hashFiles('deps.edn') }}
          restore-keys: cljdeps-

      - name: Execute tests
        id: tests
        run: lein test

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy lambda
        if: steps.tests.conclusion == 'success' && github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          lein uberjar
          aws lambda update-function-code --function-name="AuthHandler" --zip-file="fileb://target/uberjar/totem-auth-1.0-standalone.jar"

